server:
  port: 8180
  servlet:
    context-path: /security-app
spring:
  datasource:
    url: jdbc:h2:mem:mydb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false